dataflow-server:
    image: springcloud/spring-cloud-dataflow-server-local:1.4.0.RELEASE
    container_name: dataflow-server
    volumes:
      - /opt/bahmni-mart:/opt/bahmni-mart:rw
      - /var/www:/var/www:rw
      - /var/log:/var/log:rw
    ports:
      - "9393:9393"
    links:
      - postgres-server
    environment:
      - spring.dataflow.embedded.database.enabled=false
      - spring.config.location=/opt/bahmni-mart/conf/
      - spring.profiles.active=prod

postgres-server:
  image: anallytics/postgres
  volumes:
   - /var/docker-volumes/db:/var/lib/postgresql/data/:rw
  container_name: postgres-server
  ports:
   - "4432:5432"
  restart: on-failure:10
  environment:
    POSTGRES_DB_NAME: "lite_analytics"
    ANALYTICS_DB_USER: "analytics"