bahmni_mart_url: https://s3.ap-south-1.amazonaws.com/bahmni-mart/rpms/bahmni-mart.noarch.rpm
analytics_db_user: analytics
metabase_db_user: metabase
analytics_db_name: analytics
metabase_db_name: metabase
metabase_with_ssl: true
bahmni_lets_encrypt_cert_dir: "{{ bahmni_lets_encrypt_cert_dir }}"
metabase_keystore_password: "{{ metabase_keystore_password }}"
