bahmni_mart_version: "2.0.2-1"
analytics_db_user: analytics
metabase_db_user: metabase
analytics_db_name: analytics
metabase_db_name: metabase
bahmni_mart_url: "https://bahmni-mart.s3.ap-south-1.amazonaws.com/rpms/go-pipeline-rpm/bahmni-mart-2.0.2-21.noarch.rpm"
metabase_with_ssl: true
bahmni_lets_encrypt_cert_dir: "{{ bahmni_lets_encrypt_cert_dir }}"
metabase_keystore_password: "{{ metabase_keystore_password }}"
